import type { IconType } from 'react-icons';
import {
  LuArrowLeftRight,
  LuArrowRightLeft,
  LuBaby,
  LuBanknote,
  LuBook,
  LuBookOpen,
  LuBriefcase,
  LuBuilding2,
  LuBus,
  LuCar,
  LuCircleDollarSign,
  LuCircleHelp,
  LuClapperboard,
  LuCoffee,
  LuCreditCard,
  LuDog,
  LuDumbbell,
  LuEllipsis,
  LuFilm,
  LuFuel,
  LuGift,
  LuGraduationCap,
  LuHeart,
  LuHeartPulse,
  LuHouse,
  LuLandmark,
  LuPawPrint,
  LuPhone,
  LuPiggyBank,
  LuPlane,
  LuPlaneTakeoff,
  LuPlus,
  LuReceipt,
  LuScissors,
  LuSchool,
  LuShieldCheck,
  LuShirt,
  LuShoppingBag,
  LuShoppingCart,
  LuTag,
  LuTicket,
  LuTrainFront,
  LuTrendingUp,
  LuUsers,
  LuUtensils,
  LuUtensilsCrossed,
  LuWallet,
  LuWifi,
  LuZap,
} from 'react-icons/lu';

/**
 * Category icon name (as stored on the Category document) -> react-icons component.
 * Names stay Lucide-compatible so existing system and user categories resolve
 * without any data migration.
 */
export const CATEGORY_ICON_MAP: Record<string, IconType> = {
  ArrowLeftRight: LuArrowLeftRight,
  ArrowRightLeft: LuArrowRightLeft,
  Baby: LuBaby,
  Banknote: LuBanknote,
  Book: LuBook,
  BookOpen: LuBookOpen,
  Briefcase: LuBriefcase,
  Building2: LuBuilding2,
  Bus: LuBus,
  Car: LuCar,
  CircleDollarSign: LuCircleDollarSign,
  Clapperboard: LuClapperboard,
  Coffee: LuCoffee,
  CreditCard: LuCreditCard,
  Dog: LuDog,
  Dumbbell: LuDumbbell,
  Film: LuFilm,
  Fuel: LuFuel,
  Gift: LuGift,
  GraduationCap: LuGraduationCap,
  Heart: LuHeart,
  HeartPulse: LuHeartPulse,
  HelpCircle: LuCircleHelp,
  Home: LuHouse,
  House: LuHouse,
  Landmark: LuLandmark,
  MoreHorizontal: LuEllipsis,
  PawPrint: LuPawPrint,
  Pawprint: LuPawPrint,
  Phone: LuPhone,
  PiggyBank: LuPiggyBank,
  Plane: LuPlane,
  PlaneTakeoff: LuPlaneTakeoff,
  Plus: LuPlus,
  Receipt: LuReceipt,
  Scissors: LuScissors,
  School: LuSchool,
  ShieldCheck: LuShieldCheck,
  Shirt: LuShirt,
  ShoppingBag: LuShoppingBag,
  ShoppingCart: LuShoppingCart,
  Tag: LuTag,
  Ticket: LuTicket,
  Train: LuTrainFront,
  TrainFront: LuTrainFront,
  TrendingUp: LuTrendingUp,
  Users: LuUsers,
  Utensils: LuUtensils,
  UtensilsCrossed: LuUtensilsCrossed,
  Wallet: LuWallet,
  Wifi: LuWifi,
  Zap: LuZap,
};

export const DEFAULT_CATEGORY_ICON: IconType = LuTag;

/** Icon names offered in the Settings "Add Category" picker. */
export const CATEGORY_ICON_NAMES = Object.keys(CATEGORY_ICON_MAP);

export function getCategoryIcon(name?: string | null): IconType {
  if (!name) return DEFAULT_CATEGORY_ICON;
  return CATEGORY_ICON_MAP[name] || DEFAULT_CATEGORY_ICON;
}
